[tox]
envlist = py{3,310,311,312,313,314}-django52

[testenv]
allowlist_externals = ./runtests.py
setenv =
    PYTHONDONTWRITEBYTECODE=1
deps =
    django-grappelli>=4.0,<4.1
    pillow
    coverage
    ipdb
    django52: Django>=5.2,<5.3
commands = ./runtests.py {posargs}
