name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        versions:
          - python: "3"
            env: py3-django52
          - python: "3.10"
            env: py310-django52
          - python: "3.11"
            env: py311-django52
          - python: "3.12"
            env: py312-django52
          - python: "3.13"
            env: py313-django52
          - python: "3.14"
            env: py314-django52

    name: "Python ${{ matrix.versions.python }} - ${{ matrix.versions.env }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.versions.python }}
      - name: Install Dependencies
        run: pip install tox coverage
      - name: Run Tests
        run: tox -e ${{ matrix.versions.env }}